---
title: Pretty Maps with R
author: Apoorva Lal
date: Date
geometry: "margin=1in"
output:
  html_document:
    df_print: paged
    theme: flatly
    highlight: pygments
    toc: true
    toc_float: true
    toc_depth: 2
    code_folding: hide
fontsize: 12pt
indent: true
bibliography: /home/alal/Dropbox/MyLibrary.bib
csl: econometrica.csl
---

Fork of
@GrossenbacherBeautifulthematicmaps2016 (
[link](https://timogrossenbacher.ch/2016/12/beautiful-thematic-maps-with-ggplot2-only/),
[data](https://github.com/grssnbchr/thematic-maps-ggplot2) )
using the new `sf` package, more tidyverse commands, and my personal
preferences the map theme.

```{r, echo=T, include=F}
#%%
####################################################
rm(list=ls())
if (require('LalRUtils')==F) {
    library(devtools)
    devtools::install_github("apoorvalal/LalRUtils")
}
load_or_install(c('tidyverse','AER','stargazer','Hmisc',
  'magrittr','data.table', 'rgeos', 'rgdal', 'raster', 'sf',
  'viridis', 'gtable', 'grid', 'readxl'
))
####################################################
#%%
root = "/home/alal/Desktop/code/tutorials/r/thematic-maps-ggplot2/"
setwd(root)
```


```{r global_options, include=FALSE}
library(knitr)
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/', dpi=300,
                      cache=T,
                      root.dir = root,
                      echo=TRUE, include=TRUE,
                      warning=FALSE, message=FALSE)
```

# Preliminaries

```{r}
#%%
sessionInfo()
#%%
```

```{r}
#%%
theme_map <- function(...) {
  theme_minimal() +
  theme(
    text = element_text(family = "Linux Libertine Sans", color = "#22211d"),
    legend.position='bottom',
    axis.line = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    # panel.grid.minor = element_line(color = "#ebebe5", size = 0.2),
    panel.grid.major = element_line(color = "#ebebe5", size = 0.2),
    panel.grid.minor = element_blank(),
    plot.background = element_rect(fill = "#f5f5f2", color = NA),
    panel.background = element_rect(fill = "#f5f5f2", color = NA),
    legend.background = element_rect(fill = "#f5f5f2", color = NA),
    panel.border = element_blank(),
    ...
  )
}

```

# Data Ingestion and Prep

```{r}
#%%
data <- fread(paste0(root,"input/avg_age_15.csv"))
gde_15 <- st_read("input/geodata/gde-1-1-15.shp")
st_crs(gde_15) <- "+proj=somerc +lat_0=46.95240555555556
  +lon_0=7.439583333333333 +k_0=1 +x_0=600000 +y_0=200000
  +ellps=bessel +towgs84=674.374,15.056,405.346,0,0,0,0 +units=m +no_defs"

gde_15 %>% mutate(id = as.numeric(BFS_ID)) -> map_data_fortified
# now we join the thematic data
map_data <- map_data_fortified %>% left_join(data, by = c("id" = "bfs_id"))

#%%
# whole municipalities
gde_15_political <- st_read("input/geodata/g1g15.shp")
st_crs(gde_15_political) <- "+proj=somerc +lat_0=46.95240555555556
  +lon_0=7.439583333333333 +k_0=1 +x_0=600000 +y_0=200000
  +ellps=bessel +towgs84=674.374,15.056,405.346,0,0,0,0 +units=m +no_defs"

gde_15_political %>%
  mutate(id = as.numeric(GMDNR)) -> map_data_political_fortified
map_data_political_fortified %>% left_join(data, by = c("id" = "bfs_id")) ->
  map_data_political
#%% RASTER
relief <- raster("input/geodata/02-relief-georef-clipped-resampled.tif")
relief_spdf <- as(relief, "SpatialPixelsDataFrame")
relief <- as.data.frame(relief_spdf) %>%
  rename(value = `X02.relief.georef.clipped.resampled`)
# remove unnecessary variables
rm(relief_spdf, gde_15 , map_data_fortified , map_data_political_fortified)
```

# Basic Map

```{r}
#%%
p = ggplot(map_data) +
  geom_sf(aes(fill = avg_age_15),  color = "white", size = 0.1) +
  # scale_fill_viridis("Average Age 15") +
  theme_bw() +
  coord_sf() +
    # add the previously defined basic theme
  theme_map() +
  labs(x = NULL,
       y = NULL,
       title = "Switzerland's regional demographics",
       subtitle = "Average age in Swiss municipalities, 2015",
       caption = "Geometries: ThemaKart, BFS; Data: BFS, 2016")
#%%
```

```{r}
#%%
p
#%%
```

# Colour Scheme Change

```{r}
#%%
q <- p + scale_fill_viridis(option = "magma", direction = -1)
q
#%%
```

# Legend Position

```{r}
#%%
q <- p +
  # this is the main part
  scale_fill_viridis(
    option = "magma",
    direction = -1,
    name = "Average age",
    # here we use guide_colourbar because it is still a continuous scale
    guide = guide_colorbar(
      direction = "horizontal",
      barheight = unit(2, units = "mm"),
      barwidth = unit(50, units = "mm"),
      draw.ulim = F,
      title.position = 'top',
      # some shifting around
      title.hjust = 0.5,
      label.hjust = 0.5
  ))
q
#%%
```

# Discretise data

```{r}
#%%
map_data %<>% mutate(age_bin = cut(avg_age_15 ,
            breaks = quantile(avg_age_15, probs = seq(0, 1, 0.2))))
```

```{r}
p = ggplot(map_data) +
  geom_sf(aes(fill = age_bin),  color = "white", size = 0.1) +
  theme_bw() +
  coord_sf() +
    # add the previously defined basic theme
  theme_map() +
  labs(x = NULL,
       y = NULL,
       title = "Switzerland's regional demographics",
       subtitle = "Average age in Swiss municipalities, 2015",
       caption = "Geometries: ThemaKart, BFS; Data: BFS, 2016")

       # and we use guide_legend instead of guide_colourbar
p + scale_fill_viridis(
   option = "magma",
   name = "Average age",
   discrete = T,
   direction = -1,
  guide = guide_legend(
      direction = "horizontal",
      keyheight = unit(1, units = "mm"),
      keywidth =  unit(5, units = "mm"),
      title.position = 'top',
      title.hjust = 0.5,
      label.hjust = 1,
      nrow = 1,
      byrow = T,
      reverse = T,
      label.position = "bottom"
  ))
#%%
```

# Add Raster for mountains

```{r}
#%%
p = ggplot(map_data) +
# raster comes as the first layer, municipalities on top
  geom_raster(data = relief, aes(x = x,
                                y = y,
                                alpha = value)) +
  # use the "alpha hack"
  scale_alpha(name = "", range = c(0.6, 0), guide = F)  +
  geom_sf(aes(fill = age_bin),  color = "white", size = 0.05) +
  theme_bw() +
  coord_sf() +
    # add the previously defined basic theme
  theme_map() +
  labs(x = NULL,
       y = NULL,
       title = "Switzerland's regional demographics",
       subtitle = "Average age in Swiss municipalities, 2015",
       caption = "Geometries: ThemaKart, BFS; Data: BFS, 2016, Relief: swisstopo, 2016 ")

       # and we use guide_legend instead of guide_colourbar
p + scale_fill_viridis(
   option = "magma",
   name = "Average age",
   discrete = T,
   direction = -1,
  guide = guide_legend(
      direction = "horizontal",
      keyheight = unit(1, units = "mm"),
      keywidth =  unit(5, units = "mm"),
      title.position = 'top',
      title.hjust = 0.5,
      label.hjust = 1,
      nrow = 1,
      byrow = T,
      # reverse = T,
      label.position = "bottom"
  ))
#%%
```

# References
